version: "3"

services:
  app:
    image: golang:latest
    container_name: contest-go
    tty: true
    volumes:
      - ./contest:/go/src/contest
      - ./algorithm:/go/src/algorithm
      - ./template:/go/src/template
      - ./make_contest.sh:/go/make_contest.sh
    environment:
      - "GOPATH=/go"
